name: slow-tests
on: [workflow_dispatch]
jobs:
  test-illumos:
    runs-on: macos-10.15
    name: Test in illumos VM
    steps:
    - uses: actions/checkout@v2
    - name: Test on illumos
      id: test
      uses: papertigers/illumos-vm@r38
      with:
        mem: 4096
        prepare: |
          pkg install go-117
        run: |
          /opt/ooce/go-1.17/bin/go test -count=10
